### ISSUE TITLE
Warning: polyfills is not defined with grunt-contrib

### ISSUE THREAD

**Issue by leachryanb** [maenu/grunt-template-jasmine-istanbul-example#4]
I am getting the message: "Warning: polyfills is not defined" when bringing in all the contrib libs: `grunt.loadNpmTasks('grunt-contrib');`.
If I just use `grunt.loadNpmTasks('grunt-contrib-jasmine');`, all is well.

**Comment by maenu** [comment]
I can't reproduce your problem when I install `grunt-contrib` and use its tasks. Can you give more information (link to repository, package.json, Gruntfile.js, full console log using `--stack`)?

**Comment by maenu** [comment]
I guess this has to do with an update in grunt-contrib-jasmine, which added polyfills scripts, this should be solved with v0.3.0 of the template.
